services:
  app:
    container_name: quiz-app
#    build: ./frontend
    image: billyangbc/quiz:app-latest
    restart: unless-stopped
    env_file: .env
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      STRAPI_BACKEND_URL: ${STRAPI_BACKEND_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    networks:
      - strapi
    depends_on:
      - strapi

  strapi:
    container_name: quiz-strapi
#    build: ./backend
    image: billyangbc/quiz:strapi-latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi-network
    driver: bridge