name: Build and Publish Docker image

on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: Dockerfile.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/quiz:app-latest
          platforms: linux/amd64

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: Dockerfile.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USER }}/quiz:strapi-latest
          platforms: linux/amd64
